

dist: trusty
addons:
  chrome: stable
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm install
  - npm install -g gulp-cli
  - "export CHROME_BIN=chromium-browser"
  - sleep 3 # give xvfb some time to start
script: gulp test-ci